# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "telegram-bot"
	LogPath     = "/tmp/log/telegram-bot/server"

# Logger.
[logger]
    Path        = "/tmp/log/telegram-bot"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/telegram-bot/sql"
        Level  = "all"
        Stdout = true

[compiler]
    name     = "main"
    version  = "1.0.0"
    arch     = "amd64"
    system   = "linux"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "onism"
        email  = "onism68@gmail.com"